from typing import Callable, List

# Constantes de touches (valeurs int quelconques)
KEY_Z: int
KEY_S: int
KEY_O: int
KEY_L: int
KEY_R: int
KEY_P: int
KEY_Q: int
KEY_RETURN: int
KEY_UP: int
KEY_DOWN: int
KEY_SPACE: int

frame_count: int

def init(width: int, height: int, title: str = ...) -> None: ...
def run(update: Callable[[], None], draw: Callable[[], None]) -> None: ...
def quit() -> None: ...
def stop() -> None: ...
def play(channel: int, sound: int) -> None: ...
def playm(music: int, loop: bool = ...) -> None: ...

def rect(x: float, y: float, w: float, h: float, col: int) -> None: ...
def text(x: int, y: int, s: str, col: int) -> None: ...
def pset(x: int, y: int, col: int) -> None: ...
def cls(col: int = ...) -> None: ...

def btn(key: int) -> bool: ...
def btnp(key: int) -> bool: ...

class _Sound:
    def set(self, notes: str, tones: str, volumes: str, effects: str, speed: int) -> None: ...

sounds: List[_Sound]
musics: List[object]